baseURL = 'https://caijin.dev/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = true
title = '*<^_^>*'

theme = 'FixIt'
copyright = "xxxx"

[param]
version = 1.0
subtitle = 'The Best Widgets on Earth'
description = 'caijin`s site'
defaultTheme = 'dark'
externalIcon = true

[params]
[params.author]
name = "caijin"
email = ""
link = "https://caijin.dev"
avatar = "https://avatars.githubusercontent.com/u/36183188?s=400&u=69ec665b3e4ffcc40a98072d56fbaa5b044c5968&v=4"
[params.footer]
enable = true
copyright = true
author = true
since = "2024"
gov = ""
icp = ""
license = "MIT"
[params.footer.powered]
enable = true
hugoLogo = true
themeLogo = true
[params.footer.siteTime]
enable = false
animate = true
icon = "fa-solid fa-heartbeat"
pre = ""
value = ""
[params.footer.order]
powered = 2
copyright = 1
statistics = 1
visitor = 1
beian = 0

# copyright = 'fewf'


enableEmoji = true

# muilt language config
[languages]
[languages.zh]
contentDir = 'content/zh-cn'
disabled = false
languageCode = 'zh-CN'
languageDirection = 'ltr'
languageName = '简体中文'
title = '*<^_^>*'
weight = 1
[languages.zh.params]
title = '这是我的个人博客，分享技术&生活'

[languages.en]
contentDir = 'content/en'
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = '*<^_^>*'
weight = 2
[languages.en.params]
title = 'It`s my personal blog, for share tecnolige & life.'
